# Generated by Django 4.2.16 on 2024-10-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_username_user_name_remove_user_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
